// Generated by tools/generate_interface_content.py. Do not edit.
public struct AQSSInterfacePage: Equatable, Sendable {
    public let id: String
    public let title: String
    public let icon: String
    public let headline: String
    public let subtitle: String
}
public struct AQSSInterfaceFeature: Equatable, Sendable {
    public let id: String
    public let title: String
    public let detail: String
    public let explanation: String
}
public enum AQSSInterfaceContent {
    public static let pages: [AQSSInterfacePage] = [
        AQSSInterfacePage(id: "home", title: "Home", icon: "shield.lefthalf.filled", headline: "Your listening space.", subtitle: "New here? Follow the TV and phone picture guide below."),
        AQSSInterfacePage(id: "sound", title: "Sound", icon: "slider.horizontal.3", headline: "Sound, on your terms.", subtitle: "Explore volume, presets, equalizer and captions."),
        AQSSInterfacePage(id: "devices", title: "Devices", icon: "hifispeaker", headline: "A clear path to sound.", subtitle: "Choose your device and follow its picture guide."),
        AQSSInterfacePage(id: "insights", title: "Insights", icon: "chart.xyaxis.line", headline: "Know what happened.", subtitle: "Explore sample graphs and session evidence."),
        AQSSInterfacePage(id: "settings", title: "Settings", icon: "gearshape", headline: "Make space for you.", subtitle: "Choose your theme, find help and explore more features."),
    ]
    public static let future: [AQSSInterfaceFeature] = [
        AQSSInterfaceFeature(id: "voice", title: "Voice requests", detail: "Planned · proposal only", explanation: "Explore voice input and recognized words in Sound. Voice control requires device authority and checked output."),
        AQSSInterfaceFeature(id: "profiles", title: "Personal sound profiles", detail: "Planned · verified settings", explanation: "Planned profiles: save and restore confirmed preferences on supported devices."),
        AQSSInterfaceFeature(id: "supervisor", title: "Background protection", detail: "Research · device trials needed", explanation: "Background support depends on platform rules and a qualified output path. Review coverage when you return."),
        AQSSInterfaceFeature(id: "support", title: "Private support report", detail: "Planned · review before sharing", explanation: "Planned support reports: review a small, redacted record before choosing to share it."),
    ]
    public static let palettes: [String: [String: UInt32]] = [
        "midnight": ["background": 0x080F20, "surface": 0x121D33, "raised": 0x1A2842, "text": 0xF1F5FF, "muted": 0xADBDD7, "accent": 0x64DAE8, "violet": 0xB4A0FF, "warning": 0xF9CB80, "outline": 0x536A91, "control": 0x64DAE8, "controlText": 0x080F20, "controlBorder": 0x006774],
        "daylight": ["background": 0xF2F5FC, "surface": 0xFFFFFF, "raised": 0xE5ECF8, "text": 0x132238, "muted": 0x42546F, "accent": 0x006774, "violet": 0x6543AD, "warning": 0x855000, "outline": 0x667D9C, "control": 0x64DAE8, "controlText": 0x080F20, "controlBorder": 0x006774],
    ]
    public static let targetPages: [String: String] = ["chooseTV": "devices", "chooseHome": "devices", "connectionPlan": "devices", "connectionCheck": "devices", "featureExample": "sound", "guideFinish": "home", "welcome": "home", "trends": "insights", "appearance": "settings", "coverage": "home", "capability": "devices", "captions": "sound", "history": "insights", "hint": "devices", "handoff": "devices", "options": "sound", "volume": "sound", "captionOption": "sound", "sound": "sound", "equalizer": "sound", "defaults": "sound", "advanced": "settings", "route": "settings", "physical": "settings", "background": "settings", "privacy": "settings", "handoffOption": "settings", "checkHardware": "devices", "checkQualification": "devices", "checkPermission": "devices", "checkRoute": "devices", "checkRuntime": "devices", "checkEvidence": "devices"]
    public static let exampleLabel = "EXAMPLE · synthetic data"
    public static let exampleTitle = "Illustrative signal trend"
    public static let exampleUnit = "Relative level (0–100)"
    public static let exampleValues: [Double] = [18, 24, 21, 64, 40, 30, 45, 25]
}
