// Generated by tools/generate_native_feedback_contracts.py. Do not edit.
import Foundation

public enum NativeFeedbackChoice: String, Codable, Sendable {
    case rating = "rating"
    case keepThisTV = "keep_this_tv"
    case neverSwitchAutomatically = "never_switch_automatically"
}

public enum NativeFeedbackErrorCode: String, Codable, Sendable {
    case profileNotAuthorized = "PROFILE_NOT_AUTHORIZED"
    case invalidFeedback = "INVALID_FEEDBACK"
}

public struct NativeFeedbackEvent: Codable, Equatable, Sendable {
    public let schemaVersion: Int
    public let eventId: String
    public let profileId: String
    public let deviceId: String
    public let approved: Bool
    public let choice: NativeFeedbackChoice
    public let recordedAt: String

    public init(schemaVersion: Int = 1, eventId: String, profileId: String, deviceId: String, approved: Bool, choice: NativeFeedbackChoice, recordedAt: String) {
        self.schemaVersion = schemaVersion
        self.eventId = eventId
        self.profileId = profileId
        self.deviceId = deviceId
        self.approved = approved
        self.choice = choice
        self.recordedAt = recordedAt
    }

    enum CodingKeys: String, CodingKey {
        case schemaVersion = "schema_version"
        case eventId = "event_id"
        case profileId = "profile_id"
        case deviceId = "device_id"
        case approved
        case choice
        case recordedAt = "recorded_at"
    }
}

public struct NativeFeedbackSyncRequest: Codable, Equatable, Sendable {
    public let events: [NativeFeedbackEvent]

    public init(events: [NativeFeedbackEvent]) {
        self.events = events
    }
}

public struct NativeFeedbackError: Codable, Equatable, Sendable {
    public let code: NativeFeedbackErrorCode
}

public struct NativeFeedbackSyncResponse: Codable, Equatable, Sendable {
    public let schemaVersion: Int
    public let ok: Bool
    public let applied: [String]?
    public let duplicates: [String]?
    public let error: NativeFeedbackError?

    enum CodingKeys: String, CodingKey {
        case schemaVersion = "schema_version"
        case ok
        case applied
        case duplicates
        case error
    }
}

public protocol NativeFeedbackSyncing: Sendable {
    func sync(_ request: NativeFeedbackSyncRequest) async throws -> NativeFeedbackSyncResponse
}
