// Generated by tools/generate_tutorial_content.py. Do not edit.
public struct AQSSTutorialStep: Equatable, Sendable {
    public let target: String
    public let area: String
    public let title: String
    public let explanation: String
    public let example: String
}
public struct AQSSTutorialTopic: Equatable, Sendable {
    public let id: String
    public let title: String
    public let steps: [AQSSTutorialStep]
}
public enum AQSSTutorialContent {
    public static let topics: [AQSSTutorialTopic] = [
        AQSSTutorialTopic(id: "home", title: "Home and coverage", steps: [
            AQSSTutorialStep(target: "coverage", area: "home", title: "Read the coverage state", explanation: "Unknown physical state means there is no independent observation of audio output. This simulation does not provide protection.", example: "Example: A green build result cannot tell you whether a speaker produced sound."),
            AQSSTutorialStep(target: "capability", area: "home", title: "Check what is supported", explanation: "The six setup checks must be established before a control can become eligible. A connected device alone is insufficient.", example: "Example: Bluetooth may report headphones connected while the actual playback route is still unknown."),
            AQSSTutorialStep(target: "history", area: "home", title: "Understand missing history", explanation: "No observed events means the app has no session evidence to show. An empty list does not mean everything was safe.", example: "Example: A gap while the app was away remains a gap in knowledge."),
            AQSSTutorialStep(target: "hint", area: "home", title: "Treat OS hints as clues", explanation: "Foreground hints describe a system notification. They cannot verify audible output or another app's playback.", example: "Example: A route-change notice is a clue to investigate, not an observation of sound."),
        ]),
        AQSSTutorialTopic(id: "sound", title: "Sound options", steps: [
            AQSSTutorialStep(target: "options", area: "options", title: "Find the Options menu", explanation: "This highlighted button opens or hides the available option descriptions. The tutorial has opened them for you.", example: "Example: Reopen Help whenever you need this walkthrough again."),
            AQSSTutorialStep(target: "volume", area: "options", title: "Volume needs a supported output", explanation: "Volume is unavailable in this simulation. A future change needs an authorized device and verified physical result.", example: "Example: A requested volume of 40 percent would not prove the speaker reached that level."),
            AQSSTutorialStep(target: "sound", area: "options", title: "Choose a compatible preset", explanation: "Dialogue and Night are preset choices for devices that support them. The current shell cannot apply a preset.", example: "Example: Dialogue would be a proposed speech-focused preset, not a promise that speech is clearer."),
            AQSSTutorialStep(target: "equalizer", area: "options", title: "Custom EQ is device-specific", explanation: "Frequency-band controls require an explicitly supported device capability. They remain unavailable here.", example: "Example: A small 1 kHz adjustment is an illustrative setting, not a change this tutorial makes."),
        ]),
        AQSSTutorialTopic(id: "captions", title: "Captions", steps: [
            AQSSTutorialStep(target: "captionOption", area: "options", title: "Find the captions option", explanation: "Captions depend on an available track or supported caption mode. This option is unavailable until one is connected.", example: "Example: A film's authored English caption track could be selectable on a supported player."),
            AQSSTutorialStep(target: "captions", area: "home", title: "Check caption evidence", explanation: "The Home section reports what has been observed. This shell has not discovered or selected a caption track.", example: "Example: A label describing captions does not mean captions are currently displayed."),
        ]),
        AQSSTutorialTopic(id: "defaults", title: "Defaults and undo", steps: [
            AQSSTutorialStep(target: "defaults", area: "options", title: "Save only confirmed settings", explanation: "Save, restore and undo require suitable device settings and verification. This shell has no confirmed settings to use.", example: "Example: Undo would propose a return to a verified earlier setting; it cannot assume that return succeeded."),
            AQSSTutorialStep(target: "history", area: "home", title: "Look for a verified change", explanation: "A requested change and an observed result are different events. Missing history cannot supply an undo result.", example: "Example: A successful button tap is not a verified audio change."),
        ]),
        AQSSTutorialTopic(id: "advanced", title: "Advanced and privacy", steps: [
            AQSSTutorialStep(target: "advanced", area: "advanced", title: "Open Advanced options", explanation: "The highlighted button expands device, evidence, background and privacy details. You can return here without repeating other tours.", example: "Example: Use Help with advanced options for a focused refresher."),
            AQSSTutorialStep(target: "route", area: "advanced", title: "Identify the output path", explanation: "Device and route stay Unknown until qualified. A device name or connection notification cannot establish the path of sound.", example: "Example: A connected speaker may not be the speaker currently used by a player."),
            AQSSTutorialStep(target: "physical", area: "advanced", title: "Require physical observation", explanation: "This area explains why physical output remains unknown. The tutorial supplies no measurement or observation.", example: "Example: An independent measurement would need to be tied to the authorized device transaction."),
            AQSSTutorialStep(target: "background", area: "advanced", title: "Understand background limits", explanation: "This screen receives foreground hints only. Leaving the app does not establish continuing protection.", example: "Example: Events while the screen is hidden remain unknown."),
            AQSSTutorialStep(target: "privacy", area: "advanced", title: "Know what this tour stores", explanation: "The tutorial uses local text and temporary progress. It records no audio and sends no tutorial activity to a server.", example: "Example: Closing the tour lets you reopen any topic from its first step."),
        ]),
        AQSSTutorialTopic(id: "handoff", title: "Session transfer", steps: [
            AQSSTutorialStep(target: "handoffOption", area: "advanced", title: "Check transfer eligibility", explanation: "Moving a session is unavailable. A transfer requires authorized endpoints and a verified path between them.", example: "Example: Two phones signed in to an account are not, by themselves, a qualified transfer path."),
            AQSSTutorialStep(target: "handoff", area: "home", title: "Keep the handoff state truthful", explanation: "The current screen reports that no transfer path is connected. Completing this tutorial does not change that state.", example: "Example: You can finish this lesson while session transfer remains unavailable."),
        ]),
    ]
}
