// Generated by tools/generate_tutorial_content.py. Do not edit.
public struct AQSSTutorialStep: Equatable, Sendable {
    public let target: String
    public let area: String
    public let title: String
    public let explanation: String
    public let example: String
}
public struct AQSSTutorialTopic: Equatable, Sendable {
    public let id: String
    public let title: String
    public let steps: [AQSSTutorialStep]
}
public enum AQSSTutorialContent {
    public static let topics: [AQSSTutorialTopic] = [
        AQSSTutorialTopic(id: "getting_started", title: "TV & smart-home guide", steps: [
            AQSSTutorialStep(target: "welcome", area: "overview", title: "Your TV. Your comfort.", explanation: "Follow the pictures for both your TV and phone.", example: ""),
            AQSSTutorialStep(target: "chooseTV", area: "connection", title: "Which TV do you use?", explanation: "Choose the brand on your TV or remote.", example: "Example: if the remote says Samsung, choose Samsung. If you cannot find a name, choose Not sure / no TV."),
            AQSSTutorialStep(target: "chooseHome", area: "connection", title: "Use a home app?", explanation: "Choose the home app you use. Neither is fine.", example: "Example: if you say “Alexa” to an Echo speaker, choose Amazon Alexa. If you manage devices in the Google Home app, choose Google Home."),
            AQSSTutorialStep(target: "connectionPlan", area: "connection", title: "1. Connect to your TV or home device", explanation: "Follow the highlighted pictures on your TV or in its official app.", example: "Example: follow your TV maker’s app steps, then review any approval request on the television."),
            AQSSTutorialStep(target: "connectionCheck", area: "connection", title: "2. Connect to your phone", explanation: "Open your TV's official phone app and follow the pictures.", example: "Example: open the official phone app, follow its pairing prompts and review requested permissions."),
            AQSSTutorialStep(target: "guideFinish", area: "connection", title: "Your next step is ready", explanation: "Explore the controls. Replay the pictures anytime from Help.", example: "Example: open Insights and select Explore an example to see a sample graph."),
        ]),
        AQSSTutorialTopic(id: "home", title: "Home and coverage", steps: [
            AQSSTutorialStep(target: "coverage", area: "home", title: "Read the coverage state", explanation: "Unknown physical state means the sound coming from the speakers still needs an independent check.", example: "Example: a phone can show a TV as connected while the room is using a separate soundbar. The app must check the actual sound output."),
            AQSSTutorialStep(target: "capability", area: "home", title: "Check what is supported", explanation: "The six setup checks must be established before a control can become eligible. A connected device alone is insufficient.", example: "Example: Bluetooth may report headphones connected while the actual playback route is still unknown."),
            AQSSTutorialStep(target: "history", area: "home", title: "Understand missing history", explanation: "No observed events means there is no session evidence to show. Check for gaps in observation.", example: "Example: A gap while the app was away remains a gap in knowledge."),
            AQSSTutorialStep(target: "hint", area: "home", title: "Treat OS hints as clues", explanation: "Foreground hints show system notifications. Check the active speaker output separately.", example: "Example: A route-change notice is a clue to investigate, not an observation of sound."),
        ]),
        AQSSTutorialTopic(id: "sound", title: "Sound options", steps: [
            AQSSTutorialStep(target: "options", area: "options", title: "Find the Options menu", explanation: "Choose Sound to explore controls and their device requirements.", example: "Example: to learn about quieter evening listening, open Sound and read the Night preset description."),
            AQSSTutorialStep(target: "volume", area: "options", title: "Volume needs a supported output", explanation: "Volume controls require an authorized output and a verified physical result.", example: "Example: A requested volume of 40 percent would not prove the speaker reached that level."),
            AQSSTutorialStep(target: "sound", area: "options", title: "Choose a compatible preset", explanation: "Dialogue and Night presets are planned for supported sound outputs.", example: "Example: you might want speech to be easier to follow without making loud adverts louder. A future preset would still need to be tested on your speakers."),
            AQSSTutorialStep(target: "equalizer", area: "options", title: "Custom EQ is device-specific", explanation: "An equalizer balances low, middle and high sounds on a compatible device.", example: "Example: reducing bass can soften low, rumbling sounds on a supported output."),
        ]),
        AQSSTutorialTopic(id: "captions", title: "Captions", steps: [
            AQSSTutorialStep(target: "captionOption", area: "options", title: "Find the captions option", explanation: "Captions depend on an available track or supported caption mode. This option is unavailable until one is connected.", example: "Example: A film's authored English caption track could be selectable on a supported player."),
            AQSSTutorialStep(target: "captions", area: "home", title: "Check caption evidence", explanation: "Check the Sound page for caption track status.", example: "Example: check the player screen to confirm captions are displayed."),
        ]),
        AQSSTutorialTopic(id: "defaults", title: "Defaults and undo", steps: [
            AQSSTutorialStep(target: "defaults", area: "options", title: "Save only confirmed settings", explanation: "Save, restore and undo use confirmed device settings and verified results.", example: "Example: Undo returns to a verified earlier setting and checks the result."),
            AQSSTutorialStep(target: "history", area: "home", title: "Look for a verified change", explanation: "Review session evidence before using Undo.", example: "Example: A successful button tap is not a verified audio change."),
        ]),
        AQSSTutorialTopic(id: "advanced", title: "Advanced and privacy", steps: [
            AQSSTutorialStep(target: "advanced", area: "advanced", title: "Open Advanced Settings", explanation: "Open Settings, then Advanced Settings. Tap [?] beside a setting to learn how it works.", example: "Example: a disconnected switch shows cyan and “Not connected.” for two seconds, then returns to off."),
            AQSSTutorialStep(target: "route", area: "advanced", title: "Identify the output path", explanation: "Qualify the device and check its active sound output path.", example: "Example: A connected speaker may not be the speaker currently used by a player."),
            AQSSTutorialStep(target: "physical", area: "advanced", title: "Require physical observation", explanation: "Confirm sound at the speakers independently of command messages.", example: "Example: sending “lower the volume” is only a request. A separate check must confirm the intended speaker really became quieter."),
            AQSSTutorialStep(target: "background", area: "advanced", title: "Understand background limits", explanation: "This screen receives foreground hints. Review coverage again when returning to the app.", example: "Example: Events while the screen is hidden remain unknown."),
            AQSSTutorialStep(target: "privacy", area: "advanced", title: "Know what this tour stores", explanation: "Appearance and guide dismissal are saved on this phone. TV choices and tutorial progress stay in memory while the app is open.", example: "Example: Exit Home pauses your step. Back to Tutorial resumes it. Starting another tutorial clears the old paused step."),
        ]),
        AQSSTutorialTopic(id: "handoff", title: "Session transfer", steps: [
            AQSSTutorialStep(target: "handoffOption", area: "advanced", title: "Check transfer eligibility", explanation: "Moving a session is unavailable. A transfer requires authorized endpoints and a verified path between them.", example: "Example: Two phones signed in to an account are not, by themselves, a qualified transfer path."),
            AQSSTutorialStep(target: "handoff", area: "home", title: "Keep the handoff state truthful", explanation: "The current screen shows the transfer path status. Review it before moving a session.", example: "Example: review transfer eligibility on both phones before moving a session."),
        ]),
        AQSSTutorialTopic(id: "readiness", title: "Readiness checklist", steps: [
            AQSSTutorialStep(target: "checkHardware", area: "checklist", title: "Output hardware", explanation: "Unknown: no supported output device has been identified and qualified for this app.", example: "Example: A connected Bluetooth speaker is a candidate, not proof that AQSS can control it."),
            AQSSTutorialStep(target: "checkQualification", area: "checklist", title: "Qualified path", explanation: "Unknown: this exact device, driver and output path have not passed the required checks.", example: "Example: qualify the exact phone speaker and output path on a real device."),
            AQSSTutorialStep(target: "checkPermission", area: "checklist", title: "Permission and authority", explanation: "Unknown: permission and authority for a supported action have not been established. This checklist requests neither.", example: "Example: pair OS permission with device-specific authorization before a change."),
            AQSSTutorialStep(target: "checkRoute", area: "checklist", title: "Output route", explanation: "Unknown: there is no verified path from an authorized action to the intended output.", example: "Example: Headphones can be connected without being the active playback route."),
            AQSSTutorialStep(target: "checkRuntime", area: "checklist", title: "Runtime eligibility", explanation: "Unknown: there is no qualified running protection path. This screen only receives foreground hints.", example: "Example: review the observation gap after returning to the app."),
            AQSSTutorialStep(target: "checkEvidence", area: "checklist", title: "Independent observation", explanation: "Unknown: there is no independent observation tied to an authorized device transaction.", example: "Example: A device saying that a command succeeded is not independent evidence of audible output."),
        ]),
    ]
    public static let choices: [String: [AQSSTutorialChoice]] = [
        "chooseTV": [
            AQSSTutorialChoice(id: "samsung", title: "Samsung", icon: "tv", detail: "Find the exact Samsung model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            AQSSTutorialChoice(id: "lg", title: "LG", icon: "tv", detail: "Find the exact LG model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            AQSSTutorialChoice(id: "sony", title: "Sony", icon: "tv", detail: "Find the exact Sony model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            AQSSTutorialChoice(id: "tcl", title: "TCL", icon: "tv", detail: "Find the exact TCL model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            AQSSTutorialChoice(id: "hisense", title: "Hisense", icon: "tv", detail: "Find the exact Hisense model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            AQSSTutorialChoice(id: "vizio", title: "Vizio", icon: "tv", detail: "Find the exact Vizio model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            AQSSTutorialChoice(id: "philips", title: "Philips", icon: "tv", detail: "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            AQSSTutorialChoice(id: "sharp", title: "Sharp", icon: "tv", detail: "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            AQSSTutorialChoice(id: "roku", title: "Roku-branded TV", icon: "tv", detail: "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            AQSSTutorialChoice(id: "insignia", title: "Insignia", icon: "tv", detail: "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            AQSSTutorialChoice(id: "other", title: "Another brand", icon: "tv", detail: "Find the TV brand and model on its label or in its About menu. Use the manufacturer’s instructions to check which phone or smart-home connections it supports."),
            AQSSTutorialChoice(id: "unsure", title: "Not sure / no TV", icon: "tv", detail: "You can explore without a TV. Later, look for the brand and model on the TV label or ask someone to help you find it in the About menu."),
        ],
        "chooseHome": [
            AQSSTutorialChoice(id: "alexa", title: "Amazon Alexa", icon: "speaker", detail: "In the Alexa app, check your exact TV model for a compatible skill and follow the maker’s account-linking steps."),
            AQSSTutorialChoice(id: "google", title: "Google Home", icon: "house", detail: "In Google Home, check your exact TV model, follow the maker’s setup instructions and review requested permissions."),
            AQSSTutorialChoice(id: "both", title: "Both apps", icon: "house", detail: "Check your TV maker’s instructions for each app separately and follow each app’s approval steps."),
            AQSSTutorialChoice(id: "neither", title: "Neither / not sure", icon: "questionmark.circle", detail: "No smart-home account is needed to explore. Keep using your TV remote. A future direct TV connection would still need a supported model and your permission."),
        ],
    ]
    public static let connectionStages: [AQSSConnectionStage] = [
        AQSSConnectionStage(number: 1, title: "Connect to your TV or home device", detail: "Pair the device and approve access on its screen or in its official home app.", targets: ["chooseTV", "chooseHome", "connectionPlan"]),
        AQSSConnectionStage(number: 2, title: "Connect to your phone", detail: "Link your iPhone or Android phone, then check its permissions and sound connection.", targets: ["connectionCheck"]),
    ]
    public static let featureTitle = "Features"
    public static let featureNote = "Explore picture guides for your TV and phone, plus photo hints and voice input."
    public static let features: [AQSSTutorialFeature] = [
        AQSSTutorialFeature(id: "series_intro", title: "Skip series intros", detail: "On supported players with a confirmed intro segment.", availability: "planned"),
        AQSSTutorialFeature(id: "commercial_volume", title: "Lower volume during commercials", detail: "With an eligible sound path and your permission.", availability: "planned"),
        AQSSTutorialFeature(id: "remote", title: "Universal remote control", detail: "For compatible devices; controls vary by model.", availability: "planned"),
        AQSSTutorialFeature(id: "loud_sounds", title: "Reduce sudden loud sounds", detail: "Bounded volume, mute and comfort controls.", availability: "planned"),
        AQSSTutorialFeature(id: "presets", title: "Dialogue and Night sound presets", detail: "Listening options for qualified sound outputs.", availability: "planned"),
        AQSSTutorialFeature(id: "equalizer", title: "Custom equalizer", detail: "Bass, midrange and treble on supported devices.", availability: "planned"),
        AQSSTutorialFeature(id: "captions", title: "Captions, subtitles and audio description", detail: "When the media supplies compatible tracks.", availability: "planned"),
        AQSSTutorialFeature(id: "languages", title: "Audio and caption languages", detail: "Choose from the tracks supplied by the media.", availability: "planned"),
        AQSSTutorialFeature(id: "voice", title: "Voice activated control", detail: "Requests require confirmation and eligible controls.", availability: "planned"),
        AQSSTutorialFeature(id: "profiles", title: "Personal sound profiles and saved settings", detail: "Save and restore confirmed preferences.", availability: "planned"),
        AQSSTutorialFeature(id: "undo", title: "Undo changes and restore settings", detail: "For eligible changes with a known earlier setting.", availability: "planned"),
        AQSSTutorialFeature(id: "history", title: "Session history and sound insights", detail: "Real observations and gaps; examples are labeled.", availability: "planned"),
        AQSSTutorialFeature(id: "recovery", title: "Pause, resume and connection recovery", detail: "Recheck the connection before resuming controls.", availability: "planned"),
        AQSSTutorialFeature(id: "handoff", title: "Move sessions between iPhone and Android", detail: "Only through a supported, checked transfer path.", availability: "planned"),
        AQSSTutorialFeature(id: "background", title: "Background protection where supported", detail: "Subject to phone limits and a qualified sound path.", availability: "planned"),
        AQSSTutorialFeature(id: "privacy", title: "Privacy controls and private support reports", detail: "Capture choices, deletion and review before sharing.", availability: "planned"),
        AQSSTutorialFeature(id: "status", title: "Optional alerts, haptics and status widgets", detail: "Readable status with freshness and coverage gaps.", availability: "planned"),
        AQSSTutorialFeature(id: "suggestions", title: "Explainable suggestions and session recipes", detail: "Optional suggestions that you can review or dismiss.", availability: "planned"),
        AQSSTutorialFeature(id: "accessories", title: "Compatible speakers, headphones and accessories", detail: "Integrations depend on the exact device and route.", availability: "planned"),
        AQSSTutorialFeature(id: "input", title: "Voice input display and recognized words", detail: "Review the recognized words on your phone.", availability: "preview"),
    ]
    public static let featuredIDs: [String] = ["series_intro", "commercial_volume", "remote"]
    public static let pictureContinueRoutes: [String] = ["samsung_ok", "samsung_pin", "lg_pair", "google_remote", "google_setup", "tcl_models", "google_fast", "google_samsung", "google_lg", "google_roku", "google_vidaa", "google_vizio", "google_legacy", "samsung_alexa", "lg_alexa", "sony_new", "sony_legacy", "roku_alexa", "vidaa_google", "vidaa_alexa", "vizio_pair", "vizio_account", "vizio_assist", "fire_alexa", "lg_account5", "lg_account6", "google_legacy_add", "fire_setup", "roku_phone", "vizio_google", "vizio_alexa"]
    public static let previewNotice = "Picture guide"
    public static let startLabel = "Start picture setup"
    public static let moreFeaturesLabel = "More features"
    public static let helpLabel = "Need help?"
}
public struct AQSSTutorialChoice: Equatable, Sendable {
    public let id, title, icon, detail: String
}
public struct AQSSConnectionStage: Equatable, Sendable {
    public let number: Int
    public let title, detail: String
    public let targets: [String]
}
public struct AQSSTutorialFeature: Equatable, Sendable {
    public let id, title, detail, availability: String
}
