// Generated by tools/generate_tutorial_content.py. Do not edit.
public struct AQSSTutorialStep: Equatable, Sendable {
    public let target: String
    public let area: String
    public let title: String
    public let explanation: String
    public let example: String
}
public struct AQSSTutorialTopic: Equatable, Sendable {
    public let id: String
    public let title: String
    public let steps: [AQSSTutorialStep]
}
public enum AQSSTutorialContent {
    public static let topics: [AQSSTutorialTopic] = [
        AQSSTutorialTopic(id: "getting_started", title: "TV & smart-home guide", steps: [
            AQSSTutorialStep(target: "welcome", area: "overview", title: "Start with your TV", explanation: "Audio Bodyguard is being built to help with sudden loud sound. This preview does not monitor or change audio. We will show one step at a time. You can leave whenever you like.", example: "Example: a film is quiet, then an advert is much louder. Reducing that jump is a planned feature, not something this preview can do."),
            AQSSTutorialStep(target: "chooseTV", area: "connection", title: "Which TV do you use?", explanation: "Choose the name on the front of your TV or on its remote. This changes the explanation only. It does not search for or connect to your TV.", example: "Example: if the remote says Samsung, choose Samsung. If you cannot find a name, choose Not sure / no TV."),
            AQSSTutorialStep(target: "chooseHome", area: "connection", title: "Do you use a smart-home app?", explanation: "Choose the app you already use to manage devices at home. If you use neither app, that is fine. No account sign-in is needed for this guide.", example: "Example: if you say “Alexa” to an Echo speaker, choose Amazon Alexa. If you manage devices in the Google Home app, choose Google Home."),
            AQSSTutorialStep(target: "connectionPlan", area: "connection", title: "Your connection checklist", explanation: "These are preparation notes for your setup. Pairing is not available in Audio Bodyguard yet. Your TV model and the features it supports must be checked before an integration can be built.", example: "Example: finding a Samsung TV in Alexa does not let this preview control it. Audio Bodyguard would still need its own supported connection and your permission."),
            AQSSTutorialStep(target: "connectionCheck", area: "connection", title: "What does connected mean?", explanation: "Your TV is not connected to Audio Bodyguard by this guide. A name in a list only identifies a device. Changing sound would also need your permission and a separate check of what actually comes from the speakers.", example: "Example: a TV appears online, but sound is coming from a soundbar. Seeing the TV online does not prove the soundbar volume changed."),
            AQSSTutorialStep(target: "featureExample", area: "connection", title: "A simple sound example", explanation: "Planned sound presets would help with different listening needs. For now, Sound explains those controls. Insights can show an invented graph so you can learn to read it.", example: "Example: people speak quietly in a film, then an advert starts loudly. A future Night preset could request a smaller jump. This preview does not lower either sound."),
            AQSSTutorialStep(target: "guideFinish", area: "connection", title: "You know where to start", explanation: "Open the full app to explore. Devices explains connection requirements. Sound explains planned controls. Insights has an example graph. Settings has appearance choices. Help can replay this guide from any page.", example: "Example: to look at the sample graph, open Insights, then Explore an example. Its values are made up; they are not measurements from your phone."),
        ]),
        AQSSTutorialTopic(id: "home", title: "Home and coverage", steps: [
            AQSSTutorialStep(target: "coverage", area: "home", title: "Read the coverage state", explanation: "Unknown physical state means there is no independent observation of audio output. This simulation does not provide protection.", example: "Example: A green build result cannot tell you whether a speaker produced sound."),
            AQSSTutorialStep(target: "capability", area: "home", title: "Check what is supported", explanation: "The six setup checks must be established before a control can become eligible. A connected device alone is insufficient.", example: "Example: Bluetooth may report headphones connected while the actual playback route is still unknown."),
            AQSSTutorialStep(target: "history", area: "home", title: "Understand missing history", explanation: "No observed events means the app has no session evidence to show. An empty list does not mean everything was safe.", example: "Example: A gap while the app was away remains a gap in knowledge."),
            AQSSTutorialStep(target: "hint", area: "home", title: "Treat OS hints as clues", explanation: "Foreground hints describe a system notification. They cannot verify audible output or another app's playback.", example: "Example: A route-change notice is a clue to investigate, not an observation of sound."),
        ]),
        AQSSTutorialTopic(id: "sound", title: "Sound options", steps: [
            AQSSTutorialStep(target: "options", area: "options", title: "Find the Options menu", explanation: "Sound groups the available option descriptions. The tutorial has opened the Sound page and its options for you.", example: "Example: Reopen Help whenever you need this walkthrough again."),
            AQSSTutorialStep(target: "volume", area: "options", title: "Volume needs a supported output", explanation: "Volume is unavailable in this simulation. A future change needs an authorized device and verified physical result.", example: "Example: A requested volume of 40 percent would not prove the speaker reached that level."),
            AQSSTutorialStep(target: "sound", area: "options", title: "Choose a compatible preset", explanation: "Dialogue and Night are preset choices for devices that support them. The current shell cannot apply a preset.", example: "Example: Dialogue would be a proposed speech-focused preset, not a promise that speech is clearer."),
            AQSSTutorialStep(target: "equalizer", area: "options", title: "Custom EQ is device-specific", explanation: "Frequency-band controls require an explicitly supported device capability. They remain unavailable here.", example: "Example: A small 1 kHz adjustment is an illustrative setting, not a change this tutorial makes."),
        ]),
        AQSSTutorialTopic(id: "captions", title: "Captions", steps: [
            AQSSTutorialStep(target: "captionOption", area: "options", title: "Find the captions option", explanation: "Captions depend on an available track or supported caption mode. This option is unavailable until one is connected.", example: "Example: A film's authored English caption track could be selectable on a supported player."),
            AQSSTutorialStep(target: "captions", area: "home", title: "Check caption evidence", explanation: "The Sound page reports what has been observed. This shell has not discovered or selected a caption track.", example: "Example: A label describing captions does not mean captions are currently displayed."),
        ]),
        AQSSTutorialTopic(id: "defaults", title: "Defaults and undo", steps: [
            AQSSTutorialStep(target: "defaults", area: "options", title: "Save only confirmed settings", explanation: "Save, restore and undo require suitable device settings and verification. This shell has no confirmed settings to use.", example: "Example: Undo would propose a return to a verified earlier setting; it cannot assume that return succeeded."),
            AQSSTutorialStep(target: "history", area: "home", title: "Look for a verified change", explanation: "A requested change and an observed result are different events. Missing history cannot supply an undo result.", example: "Example: A successful button tap is not a verified audio change."),
        ]),
        AQSSTutorialTopic(id: "advanced", title: "Advanced and privacy", steps: [
            AQSSTutorialStep(target: "advanced", area: "advanced", title: "Open Advanced options", explanation: "Settings contains device, evidence, background and privacy details. The tutorial has opened Advanced options for you.", example: "Example: Use Help with advanced options for a focused refresher."),
            AQSSTutorialStep(target: "route", area: "advanced", title: "Identify the output path", explanation: "Device and route stay Unknown until qualified. A device name or connection notification cannot establish the path of sound.", example: "Example: A connected speaker may not be the speaker currently used by a player."),
            AQSSTutorialStep(target: "physical", area: "advanced", title: "Require physical observation", explanation: "This area explains why physical output remains unknown. The tutorial supplies no measurement or observation.", example: "Example: An independent measurement would need to be tied to the authorized device transaction."),
            AQSSTutorialStep(target: "background", area: "advanced", title: "Understand background limits", explanation: "This screen receives foreground hints only. Leaving the app does not establish continuing protection.", example: "Example: Events while the screen is hidden remain unknown."),
            AQSSTutorialStep(target: "privacy", area: "advanced", title: "Know what this tour stores", explanation: "Only appearance and whether you left the beginner guide are saved locally. TV choices and tutorial progress are temporary. No audio or tutorial analytics are uploaded.", example: "Example: Closing the tour lets you reopen any topic from its first step."),
        ]),
        AQSSTutorialTopic(id: "handoff", title: "Session transfer", steps: [
            AQSSTutorialStep(target: "handoffOption", area: "advanced", title: "Check transfer eligibility", explanation: "Moving a session is unavailable. A transfer requires authorized endpoints and a verified path between them.", example: "Example: Two phones signed in to an account are not, by themselves, a qualified transfer path."),
            AQSSTutorialStep(target: "handoff", area: "home", title: "Keep the handoff state truthful", explanation: "The current screen reports that no transfer path is connected. Completing this tutorial does not change that state.", example: "Example: You can finish this lesson while session transfer remains unavailable."),
        ]),
        AQSSTutorialTopic(id: "readiness", title: "Readiness checklist", steps: [
            AQSSTutorialStep(target: "checkHardware", area: "checklist", title: "Output hardware", explanation: "Unknown: no supported output device has been identified and qualified for this app.", example: "Example: A connected Bluetooth speaker is a candidate, not proof that AQSS can control it."),
            AQSSTutorialStep(target: "checkQualification", area: "checklist", title: "Qualified path", explanation: "Unknown: this exact device, driver and output path have not passed the required checks.", example: "Example: Passing an emulator test does not qualify a phone speaker."),
            AQSSTutorialStep(target: "checkPermission", area: "checklist", title: "Permission and authority", explanation: "Unknown: permission and authority for a supported action have not been established. This checklist requests neither.", example: "Example: An OS permission alone cannot authorize a change to another device."),
            AQSSTutorialStep(target: "checkRoute", area: "checklist", title: "Output route", explanation: "Unknown: there is no verified path from an authorized action to the intended output.", example: "Example: Headphones can be connected without being the active playback route."),
            AQSSTutorialStep(target: "checkRuntime", area: "checklist", title: "Runtime eligibility", explanation: "Unknown: there is no qualified running protection path. This screen only receives foreground hints.", example: "Example: Leaving the app may suspend it; returning does not fill the gap in observation."),
            AQSSTutorialStep(target: "checkEvidence", area: "checklist", title: "Independent observation", explanation: "Unknown: there is no independent observation tied to an authorized device transaction.", example: "Example: A device saying that a command succeeded is not independent evidence of audible output."),
        ]),
    ]
    public static let choices: [String: [AQSSTutorialChoice]] = [
        "chooseTV": [
            AQSSTutorialChoice(id: "samsung", title: "Samsung", icon: "tv", detail: "Find the exact Samsung model on its label or in its About menu. Check that model in the manufacturer’s instructions; a brand name alone does not tell us what it supports."),
            AQSSTutorialChoice(id: "lg", title: "LG", icon: "tv", detail: "Find the exact LG model on its label or in its About menu. Check that model in the manufacturer’s instructions; a brand name alone does not tell us what it supports."),
            AQSSTutorialChoice(id: "sony", title: "Sony", icon: "tv", detail: "Find the exact Sony model on its label or in its About menu. Check that model in the manufacturer’s instructions; a brand name alone does not tell us what it supports."),
            AQSSTutorialChoice(id: "tcl", title: "TCL", icon: "tv", detail: "Find the exact TCL model on its label or in its About menu. Check that model in the manufacturer’s instructions; a brand name alone does not tell us what it supports."),
            AQSSTutorialChoice(id: "hisense", title: "Hisense", icon: "tv", detail: "Find the exact Hisense model on its label or in its About menu. Check that model in the manufacturer’s instructions; a brand name alone does not tell us what it supports."),
            AQSSTutorialChoice(id: "vizio", title: "Vizio", icon: "tv", detail: "Find the exact Vizio model on its label or in its About menu. Check that model in the manufacturer’s instructions; a brand name alone does not tell us what it supports."),
            AQSSTutorialChoice(id: "other", title: "Another brand", icon: "tv", detail: "Find the TV brand and model on its label or in its About menu. Use the manufacturer’s instructions to check which phone or smart-home connections it supports."),
            AQSSTutorialChoice(id: "unsure", title: "Not sure / no TV", icon: "tv", detail: "You can explore without a TV. Later, look for the brand and model on the TV label or ask someone to help you find it in the About menu."),
        ],
        "chooseHome": [
            AQSSTutorialChoice(id: "alexa", title: "Amazon Alexa", icon: "speaker", detail: "In the Alexa app, check whether your TV maker offers a compatible skill. Follow that maker’s account-linking instructions. Seeing a TV there does not connect it to Audio Bodyguard."),
            AQSSTutorialChoice(id: "google", title: "Google Home", icon: "house", detail: "In Google Home, check whether your exact TV model can be added. Follow its maker’s setup instructions and review any requested permissions. This preview does not access your Google Home."),
            AQSSTutorialChoice(id: "both", title: "Both apps", icon: "house", detail: "Check the TV maker’s instructions for each app separately. Support in Alexa does not prove support in Google Home. This preview does not access either account."),
            AQSSTutorialChoice(id: "neither", title: "Neither / not sure", icon: "questionmark.circle", detail: "No smart-home account is needed to explore. Keep using your TV remote. A future direct TV connection would still need a supported model and your permission."),
        ],
    ]
}
public struct AQSSTutorialChoice: Equatable, Sendable {
    public let id, title, icon, detail: String
}
