// Generated by tools/generate_interface_content.py. Do not edit.
package com.aqss.nativefeedback
data class InterfacePage(val id: String, val title: String, val icon: String, val headline: String, val subtitle: String)
data class InterfaceFeature(val id: String, val title: String, val detail: String, val explanation: String)
object InterfaceContent {
    val pages = listOf(
        InterfacePage("home", "Home", "shield.lefthalf.filled", "Your listening space.", "New here? Start with the five-step tour below."),
        InterfacePage("sound", "Sound", "slider.horizontal.3", "Sound, on your terms.", "Preview volume, presets, equalizer and captions. Audio controls are not connected."),
        InterfacePage("devices", "Devices", "hifispeaker", "A clear path to sound.", "See what a future device connection will need. Pairing is not available in this preview."),
        InterfacePage("insights", "Insights", "chart.xyaxis.line", "Know what happened.", "Learn how graphs work with labeled examples. No real audio has been measured."),
        InterfacePage("settings", "Settings", "gearshape", "Make space for you.", "Choose your theme, find help and read about planned features."),
    )
    val future = listOf(
        InterfaceFeature("voice", "Voice requests", "Planned · proposal only", "A future voice request could suggest a change. Device authority and independent verification would still be required. This app is not listening for commands."),
        InterfaceFeature("profiles", "Personal sound profiles", "Planned · verified settings", "Future profiles could restore confirmed preferences on supported devices. No profile is being learned, saved or applied here."),
        InterfaceFeature("supervisor", "Background protection", "Research · device trials needed", "Continuous availability depends on platform limits and a qualified path. Leaving this app does not establish continuing protection."),
        InterfaceFeature("support", "Private support report", "Planned · review before sharing", "A future report could let you inspect a small, redacted record before sharing. No export or upload occurs here."),
    )
    val palettes = mapOf(
        "midnight" to mapOf("background" to 0xFF080F20.toInt(), "surface" to 0xFF121D33.toInt(), "raised" to 0xFF1A2842.toInt(), "text" to 0xFFF1F5FF.toInt(), "muted" to 0xFFADBDD7.toInt(), "accent" to 0xFF64DAE8.toInt(), "violet" to 0xFFB4A0FF.toInt(), "warning" to 0xFFF9CB80.toInt(), "outline" to 0xFF536A91.toInt(), "control" to 0xFF64DAE8.toInt(), "controlText" to 0xFF080F20.toInt(), "controlBorder" to 0xFF006774.toInt()),
        "daylight" to mapOf("background" to 0xFFF2F5FC.toInt(), "surface" to 0xFFFFFFFF.toInt(), "raised" to 0xFFE5ECF8.toInt(), "text" to 0xFF132238.toInt(), "muted" to 0xFF42546F.toInt(), "accent" to 0xFF006774.toInt(), "violet" to 0xFF6543AD.toInt(), "warning" to 0xFF855000.toInt(), "outline" to 0xFF667D9C.toInt(), "control" to 0xFF64DAE8.toInt(), "controlText" to 0xFF080F20.toInt(), "controlBorder" to 0xFF006774.toInt()),
    )
    val targetPages = mapOf("chooseTV" to "devices", "chooseHome" to "devices", "connectionPlan" to "devices", "connectionCheck" to "devices", "featureExample" to "sound", "guideFinish" to "home", "welcome" to "home", "trends" to "insights", "appearance" to "settings", "coverage" to "home", "capability" to "devices", "captions" to "sound", "history" to "insights", "hint" to "devices", "handoff" to "devices", "options" to "sound", "volume" to "sound", "captionOption" to "sound", "sound" to "sound", "equalizer" to "sound", "defaults" to "sound", "advanced" to "settings", "route" to "settings", "physical" to "settings", "background" to "settings", "privacy" to "settings", "handoffOption" to "settings", "checkHardware" to "devices", "checkQualification" to "devices", "checkPermission" to "devices", "checkRoute" to "devices", "checkRuntime" to "devices", "checkEvidence" to "devices")
    const val exampleLabel = "EXAMPLE · synthetic data"
    const val exampleTitle = "Illustrative signal trend"
    const val exampleUnit = "Relative level (0–100)"
    val exampleValues = listOf(18.0f, 24.0f, 21.0f, 64.0f, 40.0f, 30.0f, 45.0f, 25.0f)
}
