// Generated by tools/generate_native_feedback_contracts.py. Do not edit.
package com.aqss.nativefeedback

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class NativeFeedbackChoice {
    @SerialName("rating")
    RATING,

    @SerialName("keep_this_tv")
    KEEP_THIS_TV,

    @SerialName("never_switch_automatically")
    NEVER_SWITCH_AUTOMATICALLY,

}

@Serializable
enum class NativeFeedbackErrorCode {
    @SerialName("PROFILE_NOT_AUTHORIZED")
    PROFILE_NOT_AUTHORIZED,

    @SerialName("INVALID_FEEDBACK")
    INVALID_FEEDBACK,

}

@Serializable
data class NativeFeedbackEvent(
    @SerialName("schema_version")
    val schemaVersion: Int = 1,
    @SerialName("event_id")
    val eventId: String,
    @SerialName("profile_id")
    val profileId: String,
    @SerialName("device_id")
    val deviceId: String,
    val approved: Boolean,
    val choice: NativeFeedbackChoice,
    @SerialName("recorded_at")
    val recordedAt: String,
)

@Serializable
data class NativeFeedbackSyncRequest(
    val events: List<NativeFeedbackEvent>,
)

@Serializable
data class NativeFeedbackError(
    val code: NativeFeedbackErrorCode,
)

@Serializable
data class NativeFeedbackSyncResponse(
    @SerialName("schema_version")
    val schemaVersion: Int,
    val ok: Boolean,
    val applied: List<String>? = null,
    val duplicates: List<String>? = null,
    val error: NativeFeedbackError? = null,
)

interface NativeFeedbackSyncing {
    suspend fun sync(request: NativeFeedbackSyncRequest): NativeFeedbackSyncResponse
}
