// Generated by tools/generate_tutorial_content.py. Do not edit.
package com.aqss.nativefeedback
data class TutorialStep(val target: String, val area: String, val title: String, val explanation: String, val example: String)
data class TutorialTopic(val id: String, val title: String, val steps: List<TutorialStep>)
object TutorialContent {
    val topics: List<TutorialTopic> = listOf(
        TutorialTopic("getting_started", "TV & smart-home guide", listOf(
            TutorialStep("welcome", "overview", "Your TV. Your comfort.", "Follow the pictures for both your TV and phone.", ""),
            TutorialStep("chooseTV", "connection", "Which TV do you use?", "Choose the brand on your TV or remote.", "Example: if the remote says Samsung, choose Samsung. If you cannot find a name, choose Not sure / no TV."),
            TutorialStep("chooseHome", "connection", "Use a home app?", "Choose the home app you use. Neither is fine.", "Example: if you say “Alexa” to an Echo speaker, choose Amazon Alexa. If you manage devices in the Google Home app, choose Google Home."),
            TutorialStep("connectionPlan", "connection", "1. Connect to your TV or home device", "Follow the highlighted pictures on your TV or in its official app.", "Example: follow your TV maker’s app steps, then review any approval request on the television."),
            TutorialStep("connectionCheck", "connection", "2. Connect to your phone", "Open your TV's official phone app and follow the pictures.", "Example: open the official phone app, follow its pairing prompts and review requested permissions."),
            TutorialStep("guideFinish", "connection", "Your next step is ready", "Explore the controls. Replay the pictures anytime from Help.", "Example: open Insights and select Explore an example to see a sample graph."),
        )),
        TutorialTopic("home", "Home and coverage", listOf(
            TutorialStep("coverage", "home", "Read the coverage state", "Unknown physical state means the sound coming from the speakers still needs an independent check.", "Example: a phone can show a TV as connected while the room is using a separate soundbar. The app must check the actual sound output."),
            TutorialStep("capability", "home", "Check what is supported", "The six setup checks must be established before a control can become eligible. A connected device alone is insufficient.", "Example: Bluetooth may report headphones connected while the actual playback route is still unknown."),
            TutorialStep("history", "home", "Understand missing history", "No observed events means there is no session evidence to show. Check for gaps in observation.", "Example: A gap while the app was away remains a gap in knowledge."),
            TutorialStep("hint", "home", "Treat OS hints as clues", "Foreground hints show system notifications. Check the active speaker output separately.", "Example: A route-change notice is a clue to investigate, not an observation of sound."),
        )),
        TutorialTopic("sound", "Sound options", listOf(
            TutorialStep("options", "options", "Find the Options menu", "Choose Sound to explore controls and their device requirements.", "Example: to learn about quieter evening listening, open Sound and read the Night preset description."),
            TutorialStep("volume", "options", "Volume needs a supported output", "Volume controls require an authorized output and a verified physical result.", "Example: A requested volume of 40 percent would not prove the speaker reached that level."),
            TutorialStep("sound", "options", "Choose a compatible preset", "Dialogue and Night presets are planned for supported sound outputs.", "Example: you might want speech to be easier to follow without making loud adverts louder. A future preset would still need to be tested on your speakers."),
            TutorialStep("equalizer", "options", "Custom EQ is device-specific", "An equalizer balances low, middle and high sounds on a compatible device.", "Example: reducing bass can soften low, rumbling sounds on a supported output."),
        )),
        TutorialTopic("captions", "Captions", listOf(
            TutorialStep("captionOption", "options", "Find the captions option", "Captions depend on an available track or supported caption mode. This option is unavailable until one is connected.", "Example: A film's authored English caption track could be selectable on a supported player."),
            TutorialStep("captions", "home", "Check caption evidence", "Check the Sound page for caption track status.", "Example: check the player screen to confirm captions are displayed."),
        )),
        TutorialTopic("defaults", "Defaults and undo", listOf(
            TutorialStep("defaults", "options", "Save only confirmed settings", "Save, restore and undo use confirmed device settings and verified results.", "Example: Undo returns to a verified earlier setting and checks the result."),
            TutorialStep("history", "home", "Look for a verified change", "Review session evidence before using Undo.", "Example: A successful button tap is not a verified audio change."),
        )),
        TutorialTopic("advanced", "Advanced and privacy", listOf(
            TutorialStep("advanced", "advanced", "Open Advanced Settings", "Open Settings, then Advanced Settings. Tap [?] beside a setting to learn how it works.", "Example: a disconnected switch shows cyan and “Not connected.” for two seconds, then returns to off."),
            TutorialStep("route", "advanced", "Identify the output path", "Qualify the device and check its active sound output path.", "Example: A connected speaker may not be the speaker currently used by a player."),
            TutorialStep("physical", "advanced", "Require physical observation", "Confirm sound at the speakers independently of command messages.", "Example: sending “lower the volume” is only a request. A separate check must confirm the intended speaker really became quieter."),
            TutorialStep("background", "advanced", "Understand background limits", "This screen receives foreground hints. Review coverage again when returning to the app.", "Example: Events while the screen is hidden remain unknown."),
            TutorialStep("privacy", "advanced", "Know what this tour stores", "Appearance and your guide choice stay on this phone. TV choices and tutorial progress clear when you leave.", "Example: Closing the tour lets you reopen any topic from its first step."),
        )),
        TutorialTopic("handoff", "Session transfer", listOf(
            TutorialStep("handoffOption", "advanced", "Check transfer eligibility", "Moving a session is unavailable. A transfer requires authorized endpoints and a verified path between them.", "Example: Two phones signed in to an account are not, by themselves, a qualified transfer path."),
            TutorialStep("handoff", "home", "Keep the handoff state truthful", "The current screen shows the transfer path status. Review it before moving a session.", "Example: review transfer eligibility on both phones before moving a session."),
        )),
        TutorialTopic("readiness", "Readiness checklist", listOf(
            TutorialStep("checkHardware", "checklist", "Output hardware", "Unknown: no supported output device has been identified and qualified for this app.", "Example: A connected Bluetooth speaker is a candidate, not proof that AQSS can control it."),
            TutorialStep("checkQualification", "checklist", "Qualified path", "Unknown: this exact device, driver and output path have not passed the required checks.", "Example: qualify the exact phone speaker and output path on a real device."),
            TutorialStep("checkPermission", "checklist", "Permission and authority", "Unknown: permission and authority for a supported action have not been established. This checklist requests neither.", "Example: pair OS permission with device-specific authorization before a change."),
            TutorialStep("checkRoute", "checklist", "Output route", "Unknown: there is no verified path from an authorized action to the intended output.", "Example: Headphones can be connected without being the active playback route."),
            TutorialStep("checkRuntime", "checklist", "Runtime eligibility", "Unknown: there is no qualified running protection path. This screen only receives foreground hints.", "Example: review the observation gap after returning to the app."),
            TutorialStep("checkEvidence", "checklist", "Independent observation", "Unknown: there is no independent observation tied to an authorized device transaction.", "Example: A device saying that a command succeeded is not independent evidence of audible output."),
        )),
    )
    val choices: Map<String, List<TutorialChoice>> = mapOf(
        "chooseTV" to listOf(
            TutorialChoice("samsung", "Samsung", "tv", "Find the exact Samsung model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            TutorialChoice("lg", "LG", "tv", "Find the exact LG model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            TutorialChoice("sony", "Sony", "tv", "Find the exact Sony model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            TutorialChoice("tcl", "TCL", "tv", "Find the exact TCL model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            TutorialChoice("hisense", "Hisense", "tv", "Find the exact Hisense model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            TutorialChoice("vizio", "Vizio", "tv", "Find the exact Vizio model on its label or in its About menu. Check its supported connections in the manufacturer’s instructions."),
            TutorialChoice("philips", "Philips", "tv", "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            TutorialChoice("sharp", "Sharp", "tv", "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            TutorialChoice("roku", "Roku-branded TV", "tv", "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            TutorialChoice("insignia", "Insignia", "tv", "Tap Show steps on the checklist. Choose the operating system or remote that matches your TV, then follow the numbered pictures. Exact model support must be checked."),
            TutorialChoice("other", "Another brand", "tv", "Find the TV brand and model on its label or in its About menu. Use the manufacturer’s instructions to check which phone or smart-home connections it supports."),
            TutorialChoice("unsure", "Not sure / no TV", "tv", "You can explore without a TV. Later, look for the brand and model on the TV label or ask someone to help you find it in the About menu."),
        ),
        "chooseHome" to listOf(
            TutorialChoice("alexa", "Amazon Alexa", "speaker", "In the Alexa app, check your exact TV model for a compatible skill and follow the maker’s account-linking steps."),
            TutorialChoice("google", "Google Home", "house", "In Google Home, check your exact TV model, follow the maker’s setup instructions and review requested permissions."),
            TutorialChoice("both", "Both apps", "house", "Check your TV maker’s instructions for each app separately and follow each app’s approval steps."),
            TutorialChoice("neither", "Neither / not sure", "questionmark.circle", "No smart-home account is needed to explore. Keep using your TV remote. A future direct TV connection would still need a supported model and your permission."),
        ),
    )
    val connectionStages: List<ConnectionStage> = listOf(
        ConnectionStage(1, "Connect to your TV or home device", "Pair the device and approve access on its screen or in its official home app.", listOf("chooseTV", "chooseHome", "connectionPlan")),
        ConnectionStage(2, "Connect to your phone", "Link your iPhone or Android phone, then check its permissions and sound connection.", listOf("connectionCheck")),
    )
    const val featureTitle = "Features"
    const val featureNote = "Explore picture guides for your TV and phone, plus photo hints and voice input."
    val features: List<TutorialFeature> = listOf(
        TutorialFeature("series_intro", "Skip series intros", "On supported players with a confirmed intro segment.", "planned"),
        TutorialFeature("commercial_volume", "Lower volume during commercials", "With an eligible sound path and your permission.", "planned"),
        TutorialFeature("remote", "Universal remote control", "For compatible devices; controls vary by model.", "planned"),
        TutorialFeature("loud_sounds", "Reduce sudden loud sounds", "Bounded volume, mute and comfort controls.", "planned"),
        TutorialFeature("presets", "Dialogue and Night sound presets", "Listening options for qualified sound outputs.", "planned"),
        TutorialFeature("equalizer", "Custom equalizer", "Bass, midrange and treble on supported devices.", "planned"),
        TutorialFeature("captions", "Captions, subtitles and audio description", "When the media supplies compatible tracks.", "planned"),
        TutorialFeature("languages", "Audio and caption languages", "Choose from the tracks supplied by the media.", "planned"),
        TutorialFeature("voice", "Voice activated control", "Requests require confirmation and eligible controls.", "planned"),
        TutorialFeature("profiles", "Personal sound profiles and saved settings", "Save and restore confirmed preferences.", "planned"),
        TutorialFeature("undo", "Undo changes and restore settings", "For eligible changes with a known earlier setting.", "planned"),
        TutorialFeature("history", "Session history and sound insights", "Real observations and gaps; examples are labeled.", "planned"),
        TutorialFeature("recovery", "Pause, resume and connection recovery", "Recheck the connection before resuming controls.", "planned"),
        TutorialFeature("handoff", "Move sessions between iPhone and Android", "Only through a supported, checked transfer path.", "planned"),
        TutorialFeature("background", "Background protection where supported", "Subject to phone limits and a qualified sound path.", "planned"),
        TutorialFeature("privacy", "Privacy controls and private support reports", "Capture choices, deletion and review before sharing.", "planned"),
        TutorialFeature("status", "Optional alerts, haptics and status widgets", "Readable status with freshness and coverage gaps.", "planned"),
        TutorialFeature("suggestions", "Explainable suggestions and session recipes", "Optional suggestions that you can review or dismiss.", "planned"),
        TutorialFeature("accessories", "Compatible speakers, headphones and accessories", "Integrations depend on the exact device and route.", "planned"),
        TutorialFeature("input", "Voice input display and recognized words", "Review the recognized words on your phone.", "preview"),
    )
    val featuredIDs: List<String> = listOf("series_intro", "commercial_volume", "remote")
    val pictureContinueRoutes: List<String> = listOf("samsung_ok", "samsung_pin", "lg_pair", "google_remote", "google_setup", "tcl_models", "google_fast", "google_samsung", "google_lg", "google_roku", "google_vidaa", "google_vizio", "google_legacy", "samsung_alexa", "lg_alexa", "sony_new", "sony_legacy", "roku_alexa", "vidaa_google", "vidaa_alexa", "vizio_pair", "vizio_account", "vizio_assist", "fire_alexa", "lg_account5", "lg_account6", "google_legacy_add", "fire_setup", "roku_phone", "vizio_google", "vizio_alexa")
    const val previewNotice = "Picture guide"
    const val startLabel = "Start picture setup"
    const val moreFeaturesLabel = "More features"
    const val helpLabel = "Need help?"
}
data class TutorialChoice(val id: String, val title: String, val icon: String, val detail: String)
data class ConnectionStage(val number: Int, val title: String, val detail: String, val targets: List<String>)
data class TutorialFeature(val id: String, val title: String, val detail: String, val availability: String)
