import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts/tv_selection_native_feedback_v1.json"
SWIFT = ROOT / "native/ios/Sources/AQSSNativeFeedback/NativeFeedbackContract.swift"
KOTLIN = ROOT / "native/android/src/main/kotlin/com/aqss/nativefeedback/NativeFeedbackContract.kt"
FIELD_ORDER = ("schema_version", "event_id", "profile_id", "device_id", "approved", "choice", "recorded_at")


def camel(name):
    parts = name.split("_")
    return (parts[0] + "".join(part.title() for part in parts[1:])).replace("Tv", "TV")


def load_contract():
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    if contract.get("schema_version") != 1 or contract.get("capability") != "feedback_sync_only":
        raise ValueError("unsupported native feedback contract")
    if contract.get("platforms") != ["ios", "android"]:
        raise ValueError("unsupported native platforms")
    if set(contract.get("event_fields", {})) != set(FIELD_ORDER):
        raise ValueError("invalid native event fields")
    allowed = {"integer", "string", "boolean", "choice"}
    if any(kind not in allowed for kind in contract["event_fields"].values()):
        raise ValueError("unsupported native field type")
    return contract


def swift_source(contract):
    types = {"integer": "Int", "string": "String", "boolean": "Bool", "choice": "NativeFeedbackChoice"}
    lines = [
        "// Generated by tools/generate_native_feedback_contracts.py. Do not edit.",
        "import Foundation", "",
        "public enum NativeFeedbackChoice: String, Codable, Sendable {",
    ]
    lines += [f'    case {camel(value)} = "{value}"' for value in contract["choices"]]
    lines += ["}", "", "public enum NativeFeedbackErrorCode: String, Codable, Sendable {"]
    lines += [f'    case {camel(value.lower())} = "{value}"' for value in contract["error_codes"]]
    lines += ["}", "", "public struct NativeFeedbackEvent: Codable, Equatable, Sendable {"]
    for name in FIELD_ORDER:
        kind = contract["event_fields"][name]
        lines.append(f"    public let {camel(name)}: {types[kind]}")
    args = []
    for name in FIELD_ORDER:
        kind = contract["event_fields"][name]
        default = " = 1" if name == "schema_version" else ""
        args.append(f"{camel(name)}: {types[kind]}{default}")
    lines += ["", f"    public init({', '.join(args)}) {{"]
    lines += [f"        self.{camel(name)} = {camel(name)}" for name in FIELD_ORDER]
    lines += ["    }", "", "    enum CodingKeys: String, CodingKey {"]
    for name in FIELD_ORDER:
        suffix = f' = "{name}"' if camel(name) != name else ""
        lines.append(f"        case {camel(name)}{suffix}")
    lines += [
        "    }", "}", "",
        "public struct NativeFeedbackSyncRequest: Codable, Equatable, Sendable {",
        "    public let events: [NativeFeedbackEvent]", "",
        "    public init(events: [NativeFeedbackEvent]) {", "        self.events = events", "    }", "}", "",
        "public struct NativeFeedbackError: Codable, Equatable, Sendable {",
        "    public let code: NativeFeedbackErrorCode", "}", "",
        "public struct NativeFeedbackSyncResponse: Codable, Equatable, Sendable {",
        "    public let schemaVersion: Int", "    public let ok: Bool", "    public let applied: [String]?",
        "    public let duplicates: [String]?", "    public let error: NativeFeedbackError?", "",
        "    enum CodingKeys: String, CodingKey {", '        case schemaVersion = "schema_version"',
        "        case ok", "        case applied", "        case duplicates", "        case error", "    }", "}", "",
        "public protocol NativeFeedbackSyncing: Sendable {",
        "    func sync(_ request: NativeFeedbackSyncRequest) async throws -> NativeFeedbackSyncResponse", "}",
    ]
    return "\n".join(lines) + "\n"


def kotlin_source(contract):
    types = {"integer": "Int", "string": "String", "boolean": "Boolean", "choice": "NativeFeedbackChoice"}
    lines = [
        "// Generated by tools/generate_native_feedback_contracts.py. Do not edit.",
        "package com.aqss.nativefeedback", "", "import kotlinx.serialization.SerialName",
        "import kotlinx.serialization.Serializable", "", "@Serializable", "enum class NativeFeedbackChoice {",
    ]
    for value in contract["choices"]:
        lines += [f'    @SerialName("{value}")', f"    {value.upper()},", ""]
    lines += ["}", "", "@Serializable", "enum class NativeFeedbackErrorCode {"]
    for value in contract["error_codes"]:
        lines += [f'    @SerialName("{value}")', f"    {value.upper()},", ""]
    lines += ["}", "", "@Serializable", "data class NativeFeedbackEvent("]
    for name in FIELD_ORDER:
        if camel(name) != name:
            lines.append(f'    @SerialName("{name}")')
        kind = contract["event_fields"][name]
        default = " = 1" if name == "schema_version" else ""
        lines.append(f"    val {camel(name)}: {types[kind]}{default},")
    lines += [
        ")", "", "@Serializable", "data class NativeFeedbackSyncRequest(",
        "    val events: List<NativeFeedbackEvent>,", ")", "", "@Serializable", "data class NativeFeedbackError(",
        "    val code: NativeFeedbackErrorCode,", ")", "", "@Serializable", "data class NativeFeedbackSyncResponse(",
        '    @SerialName("schema_version")', "    val schemaVersion: Int,", "    val ok: Boolean,",
        "    val applied: List<String>? = null,", "    val duplicates: List<String>? = null,",
        "    val error: NativeFeedbackError? = null,", ")", "", "interface NativeFeedbackSyncing {",
        "    suspend fun sync(request: NativeFeedbackSyncRequest): NativeFeedbackSyncResponse", "}",
    ]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = load_contract()
    generated = {SWIFT: swift_source(contract), KOTLIN: kotlin_source(contract)}
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, text in generated.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != text]
        if stale:
            print("NATIVE_CONTRACT_DRIFT:" + ",".join(stale))
            raise SystemExit(1)
        print("NATIVE_CONTRACTS_CURRENT")
        return
    for path, text in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print("NATIVE_CONTRACTS_GENERATED")


if __name__ == "__main__":
    main()
