"""Generate presentation-only tutorial text for both native shells."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGETS = {
    "overview": {"welcome", "trends", "appearance"},
    "home": {"coverage", "capability", "captions", "history", "hint", "handoff"},
    "options": {"options", "volume", "captionOption", "sound", "equalizer", "defaults"},
    "advanced": {"advanced", "route", "physical", "background", "privacy", "handoffOption"},
    "checklist": {"checkHardware", "checkQualification", "checkPermission", "checkRoute", "checkRuntime", "checkEvidence"},
}


def validate(data):
    if set(data) != {"schema_version", "mode", "topics"} or data["schema_version"] != 1 or data["mode"] != "read_only_guidance":
        raise ValueError("invalid presentation-only tutorial contract")
    topics = data["topics"]
    if not isinstance(topics, list) or not 1 <= len(topics) <= 12:
        raise ValueError("invalid tutorial topics")
    ids = set()
    for topic in topics:
        if set(topic) != {"id", "title", "steps"} or topic["id"] in ids:
            raise ValueError("invalid or duplicate tutorial topic")
        ids.add(topic["id"])
        if not isinstance(topic["id"], str) or not topic["id"].isidentifier():
            raise ValueError("invalid topic identifier")
        if not isinstance(topic["title"], str) or not topic["title"].strip():
            raise ValueError("missing topic title")
        if not isinstance(topic["steps"], list) or not 1 <= len(topic["steps"]) <= 8:
            raise ValueError("invalid tutorial step count")
        for step in topic["steps"]:
            if set(step) != {"target", "area", "title", "explanation", "example"}:
                raise ValueError("tutorial steps may contain only presentation fields")
            if step["area"] not in TARGETS or step["target"] not in TARGETS[step["area"]]:
                raise ValueError("unknown tutorial area or target")
            if any(not isinstance(step[k], str) or not step[k].strip() or len(step[k]) > 320 for k in ("title", "explanation", "example")):
                raise ValueError("invalid tutorial text")
            if not step["example"].startswith("Example:"):
                raise ValueError("tutorial example must be labeled")
    return data


def sources(data):
    q = lambda value: json.dumps(value, ensure_ascii=False)
    keys = ("target", "area", "title", "explanation", "example")
    swift = ["// Generated by tools/generate_tutorial_content.py. Do not edit.",
             "public struct AQSSTutorialStep: Equatable, Sendable {"]
    swift += [f"    public let {key}: String" for key in keys]
    swift += ["}", "public struct AQSSTutorialTopic: Equatable, Sendable {", "    public let id: String", "    public let title: String", "    public let steps: [AQSSTutorialStep]", "}", "public enum AQSSTutorialContent {", "    public static let topics: [AQSSTutorialTopic] = ["]
    kotlin = ["// Generated by tools/generate_tutorial_content.py. Do not edit.", "package com.aqss.nativefeedback", "data class TutorialStep(" + ", ".join(f"val {key}: String" for key in keys) + ")", "data class TutorialTopic(val id: String, val title: String, val steps: List<TutorialStep>)", "object TutorialContent {", "    val topics: List<TutorialTopic> = listOf("]
    for topic in data["topics"]:
        swift += [f"        AQSSTutorialTopic(id: {q(topic['id'])}, title: {q(topic['title'])}, steps: ["]
        kotlin += [f"        TutorialTopic({q(topic['id'])}, {q(topic['title'])}, listOf("]
        for step in topic["steps"]:
            swift += ["            AQSSTutorialStep(" + ", ".join(f"{k}: {q(step[k])}" for k in keys) + "),"]
            kotlin += ["            TutorialStep(" + ", ".join(q(step[k]).replace("$", r"\$") for k in keys) + "),"]
        swift += ["        ]),"]
        kotlin += ["        )),"]
    swift += ["    ]", "}", ""]
    kotlin += ["    )", "}", ""]
    return {
        ROOT / "native/ios/Sources/AQSSNativeFeedback/TutorialContent.swift": "\n".join(swift),
        ROOT / "native/android/src/main/kotlin/com/aqss/nativefeedback/TutorialContent.kt": "\n".join(kotlin),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = validate(json.loads((ROOT / "contracts/tutorial_v1.json").read_text()))
    for path, content in sources(data).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Regenerate tutorial content: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
