"""Bounded presentation content. Example samples are never physical evidence."""
import argparse
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET_PAGES = {
    "coverage": "home", "capability": "devices", "captions": "sound",
    "history": "insights", "hint": "devices", "handoff": "devices",
    **{key: "sound" for key in ("options", "volume", "captionOption", "sound", "equalizer", "defaults")},
    **{key: "settings" for key in ("advanced", "route", "physical", "background", "privacy", "handoffOption")},
    **{key: "devices" for key in ("checkHardware", "checkQualification", "checkPermission", "checkRoute", "checkRuntime", "checkEvidence")},
}


def contrast(a, b):
    def luminance(value):
        rgb = [int(value[i:i + 2], 16) / 255 for i in (0, 2, 4)]
        rgb = [c / 12.92 if c <= .04045 else ((c + .055) / 1.055) ** 2.4 for c in rgb]
        return sum(c * w for c, w in zip(rgb, (.2126, .7152, .0722)))
    lo, hi = sorted((luminance(a), luminance(b)))
    return (hi + .05) / (lo + .05)


def validate(data):
    if set(data) != {"schema_version", "mode", "pages", "palettes", "example", "future"} or data["schema_version"] != 1 or data["mode"] != "presentation_only":
        raise ValueError("presentation fields only")
    if [p.get("id") for p in data["pages"]] != ["home", "sound", "devices", "insights", "settings"]:
        raise ValueError("five stable pages required")
    for page in data["pages"]:
        if set(page) != {"id", "title", "icon", "headline", "subtitle"} or any(not isinstance(v, str) or not v or len(v) > 160 for v in page.values()):
            raise ValueError("invalid page content")
    if set(data["palettes"]) != {"midnight", "daylight"}:
        raise ValueError("invalid palettes")
    for palette in data["palettes"].values():
        if set(palette) != {"background", "surface", "raised", "text", "muted", "accent", "violet", "warning", "outline"} or any(not isinstance(v, str) or not re.fullmatch(r"[0-9A-F]{6}", v) for v in palette.values()):
            raise ValueError("invalid palette")
        for foreground in ("text", "muted", "accent", "violet", "warning"):
            for background in ("background", "surface", "raised"):
                if contrast(palette[foreground], palette[background]) < 4.5:
                    raise ValueError(f"insufficient contrast: {foreground} on {background}")
    example = data["example"]
    if set(example) != {"kind", "label", "title", "unit", "values"} or example["kind"] != "synthetic_example" or example["label"] != "EXAMPLE · synthetic data":
        raise ValueError("chart must retain synthetic example label")
    if example["title"] != "Illustrative signal trend" or example["unit"] != "Relative level (0–100)":
        raise ValueError("synthetic example cannot claim measured units")
    if not isinstance(example["values"], list) or not 2 <= len(example["values"]) <= 32 or any(type(v) not in (int, float) or not math.isfinite(v) or not 0 <= v <= 100 for v in example["values"]):
        raise ValueError("invalid bounded example samples")
    if [item.get("id") for item in data["future"]] != ["voice", "profiles", "supervisor", "support"]:
        raise ValueError("invalid future features")
    for item in data["future"]:
        if set(item) != {"id", "title", "detail", "explanation"} or any(not isinstance(v, str) or not v or len(v) > 320 for v in item.values()):
            raise ValueError("future features contain descriptions only")
    return data


def sources(data):
    q = lambda s: json.dumps(s, ensure_ascii=False)
    page_keys = ("id", "title", "icon", "headline", "subtitle")
    feature_keys = ("id", "title", "detail", "explanation")
    sw = ["// Generated by tools/generate_interface_content.py. Do not edit."]
    kt = ["// Generated by tools/generate_interface_content.py. Do not edit.", "package com.aqss.nativefeedback"]
    for name, keys in (("InterfacePage", page_keys), ("InterfaceFeature", feature_keys)):
        sw += [f"public struct AQSS{name}: Equatable, Sendable {{"] + [f"    public let {k}: String" for k in keys] + ["}"]
        kt += [f"data class {name}(" + ", ".join(f"val {k}: String" for k in keys) + ")"]
    sw += ["public enum AQSSInterfaceContent {"]
    kt += ["object InterfaceContent {"]
    for key, name, keys in (("pages", "InterfacePage", page_keys), ("future", "InterfaceFeature", feature_keys)):
        sw += [f"    public static let {key}: [AQSS{name}] = ["]
        kt += [f"    val {key} = listOf("]
        for row in data[key]:
            sw += [f"        AQSS{name}(" + ", ".join(f"{k}: {q(row[k])}" for k in keys) + "),"]
            kt += [f"        {name}(" + ", ".join(q(row[k]).replace("$", r"\$") for k in keys) + "),"]
        sw += ["    ]"]
        kt += ["    )"]
    sw += ["    public static let palettes: [String: [String: UInt32]] = ["]
    kt += ["    val palettes = mapOf("]
    for name, palette in data["palettes"].items():
        sw += [f"        {q(name)}: [" + ", ".join(f"{q(k)}: 0x{v}" for k, v in palette.items()) + "],"]
        kt += [f"        {q(name)} to mapOf(" + ", ".join(f"{q(k)} to 0xFF{v}.toInt()" for k, v in palette.items()) + "),"]
    sw += ["    ]", "    public static let targetPages: [String: String] = [" + ", ".join(f"{q(k)}: {q(v)}" for k, v in TARGET_PAGES.items()) + "]"]
    kt += ["    )", "    val targetPages = mapOf(" + ", ".join(f"{q(k)} to {q(v)}" for k, v in TARGET_PAGES.items()) + ")"]
    for key in ("label", "title", "unit"):
        name = "example" + key.title()
        sw += [f"    public static let {name} = {q(data['example'][key])}"]
        kt += [f"    const val {name} = {q(data['example'][key])}"]
    sw += ["    public static let exampleValues: [Double] = " + str(data["example"]["values"]), "}", ""]
    kt += ["    val exampleValues = listOf(" + ", ".join(f"{float(v)}f" for v in data["example"]["values"]) + ")", "}", ""]
    return {ROOT / "native/ios/Sources/AQSSNativeFeedback/InterfaceContent.swift": "\n".join(sw), ROOT / "native/android/src/main/kotlin/com/aqss/nativefeedback/InterfaceContent.kt": "\n".join(kt)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = validate(json.loads((ROOT / "contracts/interface_v1.json").read_text()))
    for path, content in sources(data).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Regenerate interface content: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
